server:
  port: 6001
  #因为zull路由微服务 十分特殊  是总部的启动线程 所以端口号用6开头


spring:
  application:
    name: springcloud-zull
eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
  instance:
    instanceId: springcloud-zull:6001  is  already                        #自定义服务名称信息
    preferIpAddress: true                                   #访问路径可以显示IP地址

      #zuul:
      #prefix: /              #前缀 一般允许加 但处理路径目录结构完善 则不需要额外加url前缀
      #ignored-services: microservice-provider2-hystrix2,springcloud-ioc     #指定n个服务名过滤   用逗号分隔
      #现在注册中心有2个注册线程  要进行多个微服务名 过滤及设置代理名
      #routes:
      #teach-ioc1:  #zull设置多个服务代理名 要根据微服务版块名  依次设置
      #serviceId: teach-ioc1
      #path: /ioc/**
      #springcloud-ioc:
      #serviceId: springcloud-ioc
     #path: /ioc/**

zuul:
  prefix: /**
  ignored-services: springcloud-ioc
  routes:
    springcloud-ioc:
      serviceId: springcloud-ioc
      path: /**

  connectTimeoutMillis: 10000


ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

hystrix:
  command:
    default:  #全局配置hystrix
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 12000 #hystrix超时时间公式timeoutInMilliseconds = (1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout



info:
  app.name: springcloud-zull
  company.name: www.lzj.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}