server:
  port: 8001

mybatis:
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations:
    - "classpath:mybatis/mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: com.chinasoft.springcloud_util.entity            # 别名类所在包

# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  returnPageInfo: check
  params: count=countSql

logging:
  level:
    com:
      chinasoft:
        springcloud_orm1:
          dao: TRACE

spring:
  application:
    name: springcloud-orm                          #微服务的名字
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/youhuiquan?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    #使用druid数据连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid数据连接池 的持久化性能配置
    filters: stat,wall,slf4j,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000                                           # 数据库连接池的最小维持连接数


eureka:
  client:
    service-url:
      #defaultZone: http://localhost:9001/eureka
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9003.com:9003/eureka/
      #defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: springcloud-orm1:8001  is  already    #自定义服务名称信息
    prefer-ip-address: true
info:
  app.name: springcloud-orm1:8001
  company.name: www.lzj.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}